
name: 'fcbi_data_portfolio'
version: '1.0.0'
config-version: 2
profile: 'fcbi-staff-data-analyst-portfolio'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

