# -*- coding: utf-8 -*-
"""data_generation.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10xSgS7eovlDIR5chKt_Yp3b9kys3wpFg
"""

import pandas as pd
import numpy as np

np.random.seed(42)

def generate_loan_origination_data(n_rows):
    # Generate application_id and customer_id
    application_ids = np.arange(1000, 1000 + n_rows)
    customer_ids = np.random.randint(1, n_rows // 2 + 1, n_rows) # Allow multiple loans per customer

    data = {
        'application_id': application_ids,
        'customer_id': customer_ids,
        'credit_score': np.random.randint(580, 851, n_rows), # Scores from 580 to 850
        'ltv_ratio': np.random.uniform(0.5, 0.95, n_rows).round(4),
        'loan_amount': np.random.uniform(10000, 1000000, n_rows).round(2),
        'tier': np.random.choice(['A', 'B', 'C', 'D'], n_rows, p=[0.4, 0.3, 0.2, 0.1]),
        'interest_rate': np.random.uniform(3.0, 15.0, n_rows).round(2),
        'origination_date': pd.to_datetime('2022-01-01') + pd.to_timedelta(np.random.randint(0, 730, n_rows), unit='D') # Covering 2 years
    }

    df = pd.DataFrame(data)
    return df

def generate_loan_performance_history(origination_df, n_rows_performance):
    # Randomly select application_ids from the origination data
    performance_app_ids = np.random.choice(origination_df['application_id'].values, n_rows_performance, replace=True)
    performance_df = pd.DataFrame({'application_id': performance_app_ids})

    # Merge with origination data to get loan_amount and origination_date
    performance_df = performance_df.merge(origination_df[['application_id', 'loan_amount', 'origination_date']],
                                            on='application_id', how='left')

    # Generate report_date after origination_date
    days_after_origination = np.random.randint(30, 365 * 2, n_rows_performance) # 1 month to 2 years after origination
    performance_df['report_date'] = performance_df['origination_date'] + pd.to_timedelta(days_after_origination, unit='D')

    # Generate status and days_past_due
    status_choices = ['Current', 'Late 30', 'Late 60', 'Default']
    status_probs = [0.8, 0.1, 0.05, 0.05] # Probabilities for each status
    performance_df['status'] = np.random.choice(status_choices, n_rows_performance, p=status_probs)

    performance_df['days_past_due'] = 0
    performance_df.loc[performance_df['status'] == 'Late 30', 'days_past_due'] = np.random.randint(30, 60, (performance_df['status'] == 'Late 30').sum())
    performance_df.loc[performance_df['status'] == 'Late 60', 'days_past_due'] = np.random.randint(60, 90, (performance_df['status'] == 'Late 60').sum())
    performance_df.loc[performance_df['status'] == 'Default', 'days_past_due'] = np.random.randint(90, 180, (performance_df['status'] == 'Default').sum())

    # Generate balance, ensuring it's less than the original loan_amount
    performance_df['balance'] = (performance_df['loan_amount'] * np.random.uniform(0.1, 0.99, n_rows_performance)).round(2)

    # Drop temporary columns used for generation
    performance_df = performance_df.drop(columns=['loan_amount', 'origination_date'])

    return performance_df

# 4. Call the generate_loan_origination_data function
loan_origination_data = generate_loan_origination_data(n_rows=25000)

# 5. Call the generate_loan_performance_history function
loan_performance_history = generate_loan_performance_history(loan_origination_data, n_rows_performance=150000)

# 6. Display the first 5 rows and the info of both generated DataFrames
print("### Loan Origination Data (First 5 Rows):\n")
print(loan_origination_data.head())
print("\n### Loan Origination Data Info:\n")
loan_origination_data.info()

print("\n### Loan Performance History (First 5 Rows):\n")
print(loan_performance_history.head())
print("\n### Loan Performance History Info:\n")
loan_performance_history.info()

# -----------------------------------------------------------
# SAVE OUTPUT FILES TO GOOGLE COLAB DIRECTORY
# -----------------------------------------------------------

# Save DataFrames as CSV files in the Colab working directory
loan_origination_data.to_csv('/content/loan_origination_data.csv', index=False)
loan_performance_history.to_csv('/content/loan_performance_history.csv', index=False)

print("\n### Files Successfully Saved to Google Colab Directory ###")
print("Saved: /content/loan_origination_data.csv")
print("Saved: /content/loan_performance_history.csv")

import pandas as pd
import pandas_gbq

project_id = 'driiiportfolio'

# Read the CSV files generated in the previous step
loan_origination_data_df = pd.read_csv('/content/data/raw/loan_origination_data.csv', parse_dates=['origination_date'])
loan_performance_history_df = pd.read_csv('/content/data/raw/loan_performance_history.csv', parse_dates=['report_date'])

loan_origination_data_df.to_gbq(
    destination_table='raw.loan_origination_data',
    project_id=project_id,
    if_exists='replace'
)
loan_performance_history_df.to_gbq(
    destination_table='raw.loan_performance_history',
    project_id=project_id,
    if_exists='replace'
)

print("Data ingested to BigQuery raw layer.")